name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '.{7,}'
          flags: 'gm'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          error: 'Commit message is too short'
      - name: Chech if includes only letters
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '[A-Za-z]+'
          flags: 'gm'
          error: 'Only letters are allowed!!1'
  
